//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.1432.
// 
namespace ScalaWS.PlanGenerator {
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="planGeneratorServiceSoapBinding", Namespace="http://v1.2.api.cm.scala.com")]
    public partial class planGeneratorService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getPlanStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback generatePlansOperationCompleted;
        
        private System.Threading.SendOrPostCallback generatePlansByDistServerOperationCompleted;
        
        private System.Threading.SendOrPostCallback getStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDistributionServersOperationCompleted;
        
        /// <remarks/>
        public planGeneratorService() {
            this.Url = "http://localhost:8080/ContentManager/api/v1.2/planGenerator";
        }
        
        /// <remarks/>
        public event getPlanStatusCompletedEventHandler getPlanStatusCompleted;
        
        /// <remarks/>
        public event generatePlansCompletedEventHandler generatePlansCompleted;
        
        /// <remarks/>
        public event generatePlansByDistServerCompletedEventHandler generatePlansByDistServerCompleted;
        
        /// <remarks/>
        public event getStatusCompletedEventHandler getStatusCompleted;
        
        /// <remarks/>
        public event getDistributionServersCompletedEventHandler getDistributionServersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://v1.2.api.cm.scala.com", ResponseNamespace="http://v1.2.api.cm.scala.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("distributionServers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public distributionStatusTO getPlanStatus([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string taskUuid) {
            object[] results = this.Invoke("getPlanStatus", new object[] {
                        taskUuid});
            return ((distributionStatusTO)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPlanStatus(string taskUuid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPlanStatus", new object[] {
                        taskUuid}, callback, asyncState);
        }
        
        /// <remarks/>
        public distributionStatusTO EndgetPlanStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((distributionStatusTO)(results[0]));
        }
        
        /// <remarks/>
        public void getPlanStatusAsync(string taskUuid) {
            this.getPlanStatusAsync(taskUuid, null);
        }
        
        /// <remarks/>
        public void getPlanStatusAsync(string taskUuid, object userState) {
            if ((this.getPlanStatusOperationCompleted == null)) {
                this.getPlanStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPlanStatusOperationCompleted);
            }
            this.InvokeAsync("getPlanStatus", new object[] {
                        taskUuid}, this.getPlanStatusOperationCompleted, userState);
        }
        
        private void OngetPlanStatusOperationCompleted(object arg) {
            if ((this.getPlanStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPlanStatusCompleted(this, new getPlanStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://v1.2.api.cm.scala.com", ResponseNamespace="http://v1.2.api.cm.scala.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("distributionServerTasks", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public distributionServerTaskTO[] generatePlans([System.Xml.Serialization.XmlElementAttribute("playerIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int[] playerIds) {
            object[] results = this.Invoke("generatePlans", new object[] {
                        playerIds});
            return ((distributionServerTaskTO[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingeneratePlans(int[] playerIds, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("generatePlans", new object[] {
                        playerIds}, callback, asyncState);
        }
        
        /// <remarks/>
        public distributionServerTaskTO[] EndgeneratePlans(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((distributionServerTaskTO[])(results[0]));
        }
        
        /// <remarks/>
        public void generatePlansAsync(int[] playerIds) {
            this.generatePlansAsync(playerIds, null);
        }
        
        /// <remarks/>
        public void generatePlansAsync(int[] playerIds, object userState) {
            if ((this.generatePlansOperationCompleted == null)) {
                this.generatePlansOperationCompleted = new System.Threading.SendOrPostCallback(this.OngeneratePlansOperationCompleted);
            }
            this.InvokeAsync("generatePlans", new object[] {
                        playerIds}, this.generatePlansOperationCompleted, userState);
        }
        
        private void OngeneratePlansOperationCompleted(object arg) {
            if ((this.generatePlansCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generatePlansCompleted(this, new generatePlansCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://v1.2.api.cm.scala.com", ResponseNamespace="http://v1.2.api.cm.scala.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("distributionServerTask", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public distributionServerTaskTO generatePlansByDistServer([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string uuid) {
            object[] results = this.Invoke("generatePlansByDistServer", new object[] {
                        uuid});
            return ((distributionServerTaskTO)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingeneratePlansByDistServer(string uuid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("generatePlansByDistServer", new object[] {
                        uuid}, callback, asyncState);
        }
        
        /// <remarks/>
        public distributionServerTaskTO EndgeneratePlansByDistServer(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((distributionServerTaskTO)(results[0]));
        }
        
        /// <remarks/>
        public void generatePlansByDistServerAsync(string uuid) {
            this.generatePlansByDistServerAsync(uuid, null);
        }
        
        /// <remarks/>
        public void generatePlansByDistServerAsync(string uuid, object userState) {
            if ((this.generatePlansByDistServerOperationCompleted == null)) {
                this.generatePlansByDistServerOperationCompleted = new System.Threading.SendOrPostCallback(this.OngeneratePlansByDistServerOperationCompleted);
            }
            this.InvokeAsync("generatePlansByDistServer", new object[] {
                        uuid}, this.generatePlansByDistServerOperationCompleted, userState);
        }
        
        private void OngeneratePlansByDistServerOperationCompleted(object arg) {
            if ((this.generatePlansByDistServerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generatePlansByDistServerCompleted(this, new generatePlansByDistServerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://v1.2.api.cm.scala.com", ResponseNamespace="http://v1.2.api.cm.scala.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("distributionServers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public distributionServerTaskTO getStatus([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string taskUuid) {
            object[] results = this.Invoke("getStatus", new object[] {
                        taskUuid});
            return ((distributionServerTaskTO)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetStatus(string taskUuid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getStatus", new object[] {
                        taskUuid}, callback, asyncState);
        }
        
        /// <remarks/>
        public distributionServerTaskTO EndgetStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((distributionServerTaskTO)(results[0]));
        }
        
        /// <remarks/>
        public void getStatusAsync(string taskUuid) {
            this.getStatusAsync(taskUuid, null);
        }
        
        /// <remarks/>
        public void getStatusAsync(string taskUuid, object userState) {
            if ((this.getStatusOperationCompleted == null)) {
                this.getStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetStatusOperationCompleted);
            }
            this.InvokeAsync("getStatus", new object[] {
                        taskUuid}, this.getStatusOperationCompleted, userState);
        }
        
        private void OngetStatusOperationCompleted(object arg) {
            if ((this.getStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getStatusCompleted(this, new getStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://v1.2.api.cm.scala.com", ResponseNamespace="http://v1.2.api.cm.scala.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("distributionServers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public distributionServerTO[] getDistributionServers() {
            object[] results = this.Invoke("getDistributionServers", new object[0]);
            return ((distributionServerTO[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetDistributionServers(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getDistributionServers", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public distributionServerTO[] EndgetDistributionServers(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((distributionServerTO[])(results[0]));
        }
        
        /// <remarks/>
        public void getDistributionServersAsync() {
            this.getDistributionServersAsync(null);
        }
        
        /// <remarks/>
        public void getDistributionServersAsync(object userState) {
            if ((this.getDistributionServersOperationCompleted == null)) {
                this.getDistributionServersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDistributionServersOperationCompleted);
            }
            this.InvokeAsync("getDistributionServers", new object[0], this.getDistributionServersOperationCompleted, userState);
        }
        
        private void OngetDistributionServersOperationCompleted(object arg) {
            if ((this.getDistributionServersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDistributionServersCompleted(this, new getDistributionServersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://v1.1.api.cm.scala.com")]
    public partial class distributionStatusTO {
        
        private int completedPlayersField;
        
        private bool completedPlayersFieldSpecified;
        
        private bool confirmedField;
        
        private string confirmedByField;
        
        private int connectedPlayersField;
        
        private bool connectedPlayersFieldSpecified;
        
        private System.DateTime lastSyncField;
        
        private bool lastSyncFieldSpecified;
        
        private long mediaSizeField;
        
        private bool mediaSizeFieldSpecified;
        
        private bool multicastField;
        
        private System.DateTime nextSyncField;
        
        private bool nextSyncFieldSpecified;
        
        private bool rejectedField;
        
        private string rejectedByField;
        
        private distributionStateEnum stateField;
        
        private bool stateFieldSpecified;
        
        private int syncedPlayersField;
        
        private bool syncedPlayersFieldSpecified;
        
        private string taskIdField;
        
        private int totalPlayersField;
        
        private bool totalPlayersFieldSpecified;
        
        private long transmissionSizeField;
        
        private bool transmissionSizeFieldSpecified;
        
        private int updatedPlayersField;
        
        private bool updatedPlayersFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int completedPlayers {
            get {
                return this.completedPlayersField;
            }
            set {
                this.completedPlayersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool completedPlayersSpecified {
            get {
                return this.completedPlayersFieldSpecified;
            }
            set {
                this.completedPlayersFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool confirmed {
            get {
                return this.confirmedField;
            }
            set {
                this.confirmedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string confirmedBy {
            get {
                return this.confirmedByField;
            }
            set {
                this.confirmedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int connectedPlayers {
            get {
                return this.connectedPlayersField;
            }
            set {
                this.connectedPlayersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool connectedPlayersSpecified {
            get {
                return this.connectedPlayersFieldSpecified;
            }
            set {
                this.connectedPlayersFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime lastSync {
            get {
                return this.lastSyncField;
            }
            set {
                this.lastSyncField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastSyncSpecified {
            get {
                return this.lastSyncFieldSpecified;
            }
            set {
                this.lastSyncFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long mediaSize {
            get {
                return this.mediaSizeField;
            }
            set {
                this.mediaSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mediaSizeSpecified {
            get {
                return this.mediaSizeFieldSpecified;
            }
            set {
                this.mediaSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool multicast {
            get {
                return this.multicastField;
            }
            set {
                this.multicastField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime nextSync {
            get {
                return this.nextSyncField;
            }
            set {
                this.nextSyncField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nextSyncSpecified {
            get {
                return this.nextSyncFieldSpecified;
            }
            set {
                this.nextSyncFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool rejected {
            get {
                return this.rejectedField;
            }
            set {
                this.rejectedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rejectedBy {
            get {
                return this.rejectedByField;
            }
            set {
                this.rejectedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public distributionStateEnum state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stateSpecified {
            get {
                return this.stateFieldSpecified;
            }
            set {
                this.stateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int syncedPlayers {
            get {
                return this.syncedPlayersField;
            }
            set {
                this.syncedPlayersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool syncedPlayersSpecified {
            get {
                return this.syncedPlayersFieldSpecified;
            }
            set {
                this.syncedPlayersFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string taskId {
            get {
                return this.taskIdField;
            }
            set {
                this.taskIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int totalPlayers {
            get {
                return this.totalPlayersField;
            }
            set {
                this.totalPlayersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalPlayersSpecified {
            get {
                return this.totalPlayersFieldSpecified;
            }
            set {
                this.totalPlayersFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long transmissionSize {
            get {
                return this.transmissionSizeField;
            }
            set {
                this.transmissionSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transmissionSizeSpecified {
            get {
                return this.transmissionSizeFieldSpecified;
            }
            set {
                this.transmissionSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int updatedPlayers {
            get {
                return this.updatedPlayersField;
            }
            set {
                this.updatedPlayersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatedPlayersSpecified {
            get {
                return this.updatedPlayersFieldSpecified;
            }
            set {
                this.updatedPlayersFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://v1.1.api.cm.scala.com")]
    public enum distributionStateEnum {
        
        /// <remarks/>
        IDLE,
        
        /// <remarks/>
        SYNCING,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://v1.1.api.cm.scala.com")]
    public partial class distributionServerTO {
        
        private distributionDriverEnum distributionDriverEnumField;
        
        private bool distributionDriverEnumFieldSpecified;
        
        private string nameField;
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public distributionDriverEnum distributionDriverEnum {
            get {
                return this.distributionDriverEnumField;
            }
            set {
                this.distributionDriverEnumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool distributionDriverEnumSpecified {
            get {
                return this.distributionDriverEnumFieldSpecified;
            }
            set {
                this.distributionDriverEnumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://v1.1.api.cm.scala.com")]
    public enum distributionDriverEnum {
        
        /// <remarks/>
        IP_P2P,
        
        /// <remarks/>
        IP_CACHE,
        
        /// <remarks/>
        IP_MULTICAST,
        
        /// <remarks/>
        HUGHES_NET,
        
        /// <remarks/>
        FILE,
        
        /// <remarks/>
        Z_BAND,
        
        /// <remarks/>
        KENCAST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://v1.1.api.cm.scala.com")]
    public partial class distributionServerTaskTO {
        
        private string taskField;
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string task {
            get {
                return this.taskField;
            }
            set {
                this.taskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void getPlanStatusCompletedEventHandler(object sender, getPlanStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPlanStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPlanStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public distributionStatusTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((distributionStatusTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void generatePlansCompletedEventHandler(object sender, generatePlansCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class generatePlansCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal generatePlansCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public distributionServerTaskTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((distributionServerTaskTO[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void generatePlansByDistServerCompletedEventHandler(object sender, generatePlansByDistServerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class generatePlansByDistServerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal generatePlansByDistServerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public distributionServerTaskTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((distributionServerTaskTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void getStatusCompletedEventHandler(object sender, getStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public distributionServerTaskTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((distributionServerTaskTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void getDistributionServersCompletedEventHandler(object sender, getDistributionServersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDistributionServersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDistributionServersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public distributionServerTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((distributionServerTO[])(this.results[0]));
            }
        }
    }
}
